### PR TITLE
Add QA config

### PR DESCRIPTION
**Pull request by mark-cooper**
QA is a companion to PROD upgrades.

- Update QA config first
- Deploy, reindex and review

When ready update PROD to match QA config.

### CODE REVIEW

**Comment by fordmadox** [comment]
@mark-cooper the ASpace version should be ```fordmadox/archivesspace:2.4.1.yale.20190822``` right?  will merge after the weekend, but just checking in about that part.

**Comment by fordmadox** [comment]
will also need the new https://github.com/YaleArchivesSpace/yale_series_titles plugin, etc., if this new "qa" directory is meant to mirror what we want to upgrade PROD to. that plugin is what's forcing us to do a full re-index of the PUI.

**Comment by mark-cooper** [comment]
@fordmadox right, this PR is simply a starting point (a copy of the prod config) for you to update however you need. You should update the docker image version and plugins accordingly - I don't know the specifics. This config will be used for a new instance (qa*) that will reindex a copy of the prod database before the prod config is updated (to match what was used for qa) and the qa solr index restored to prod. That's my understanding, please let me know asap if I'm incorrect on any detail.

* qa will be made available online for you to review before the database is restored so you can do some initial checking that the right config etc. is in place.

**Comment by fordmadox** [comment]
Thanks, @mark-cooper .  I've got things merged, and I've also updated "qa" to be a lot more like TEST, so that it has the "yale_series_title" plugin enabled. 

One question:  can you provide a bit more info about the availability of the "qa" instance? I've been assuming that it would essentially be locked down, but if that's not the case then I would think that I should also update this "qa" directory to be even more like TEST so that it won't have Google Analytics enabled and so that it will have, at the very least, a "no crawl" directive.

**Comment by mark-cooper** [comment]
@fordmadox the QA site can be IP restricted and / or with basic auth applied. I asked Steelsen to provide the range of ip addresses to allow in a related Zendesk ticket.

**Pull request merged**
